#!/usr/bin/env node
/**
 * fetch-fonts.mjs — pull the woff2 subsets of the three Plex cuts into
 * public/fonts and write src/fonts.css.
 *
 * Self-hosted rather than linked: on a throttled connection a third-party font
 * origin costs a DNS lookup, a TLS handshake and a render-blocking stylesheet
 * before the first byte of a font arrives.
 *
 * Subset to the characters this page actually sets: printable ASCII plus every
 * character that appears in the content file (the ohm sign, the true minus, the
 * en dash, plus or minus, and so on). A full latin subset of IBM Plex Sans is
 * 45 kB a weight; this is a few kB, and on a throttled connection those bytes
 * come out of the hero image's budget.
 *
 *   node scripts/fetch-fonts.mjs
 */

import { mkdir, writeFile, readFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'

// Google serves woff2 only to browsers that ask like one.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36'
const FONT_DIR = 'public/fonts'
const CSS_OUT = 'src/fonts.css'
/** Every string on the page lives here, so every glyph the page needs does too. */
const CONTENT = 'src/content/product.ts'

const CUTS = [
  { family: 'IBM Plex Sans', weight: 400 },
  { family: 'IBM Plex Sans', weight: 600 },
  { family: 'IBM Plex Sans Condensed', weight: 600 },
  { family: 'IBM Plex Mono', weight: 400 },
]

async function charset() {
  const chars = new Set()
  for (let code = 32; code <= 126; code++) chars.add(String.fromCharCode(code))
  for (const char of await readFile(CONTENT, 'utf8')) {
    if (char.codePointAt(0) > 31) chars.add(char)
  }
  return [...chars].sort().join('')
}

const text = await charset()
console.log(`  subsetting to ${text.length} characters
`)

const faces = []
for (const cut of CUTS) {
  const url = new URL('https://fonts.googleapis.com/css2')
  url.searchParams.set('family', `${cut.family}:wght@${cut.weight}`)
  url.searchParams.set('text', text)
  url.searchParams.set('display', 'swap')
  const css = await (await fetch(url, { headers: { 'user-agent': UA } })).text()
  const fontUrl = /src:\s*url\(([^)]+)\)/.exec(css)?.[1]
  if (!fontUrl) throw new Error(`No woff2 returned for ${cut.family} ${cut.weight}`)
  faces.push({ family: cut.family, weight: String(cut.weight), url: fontUrl })
}

await mkdir(FONT_DIR, { recursive: true })
const rules = []
let total = 0
for (const face of faces) {
  const slug = `${face.family.toLowerCase().replaceAll(' ', '-')}-${face.weight}.woff2`
  const bytes = Buffer.from(
    await (await fetch(face.url, { headers: { 'user-agent': UA } })).arrayBuffer(),
  )
  await writeFile(path.join(FONT_DIR, slug), bytes)
  total += bytes.length
  process.stdout.write(`  ${slug.padEnd(44)} ${(bytes.length / 1024).toFixed(1)} kB\n`)
  rules.push(
    [
      '@font-face {',
      `  font-family: '${face.family}';`,
      '  font-style: normal;',
      `  font-weight: ${face.weight};`,
      '  font-display: swap;',
      `  src: url('/fonts/${slug}') format('woff2');`,
      '}',
    ].join('\n'),
  )
}

const header = [
  '/*',
  ' * Generated by scripts/fetch-fonts.mjs. Do not edit by hand.',
  ' *',
  ' * IBM Plex, self-hosted and subset to the glyphs this page sets. Linking',
  ' * Google Fonts instead cost a third-party DNS lookup and TLS handshake in',
  ' * front of a render-blocking stylesheet.',
  ' */',
  '',
].join('\n')

await writeFile(CSS_OUT, `${header}${rules.join('\n\n')}\n`, 'utf8')
console.log(`\n  ${faces.length} faces, ${(total / 1024).toFixed(0)} kB total -> ${CSS_OUT}`)
